/**
 * AIQ Adaptive Assessment Engine — tRPC Router (v2)
 *
 * Architecture:
 * - LLM-first: every question is generated by the adaptive engine using the user's
 *   role, seniority, sector, AI usage level, and current capability gap profile.
 * - Async pre-generation: after submitAnswer, the next item is generated in the
 *   background and stored in session_metadata_json.pendingNextItem. The next
 *   session query serves it instantly (zero perceived latency).
 * - One-time baseline: the first session is flagged as isBaseline in metadata.
 *   All subsequent sessions receive prior capability scores for calibration from Q1.
 * - Rich item types: scenario_critique / output_improvement / error_detection
 *   return an aiOutput block; data_interpretation returns a dataContext block.
 *   These are rendered with distinct visual treatments in the UI.
 * - Static items are kept as an emergency fallback only (never served in normal flow).
 */

import { TRPCError } from "@trpc/server";
import { and, desc, eq, isNull, notLike, like } from "drizzle-orm";
import { nanoid } from "nanoid";
import { z } from "zod";
import {
  ailOrgContext,
  assessmentAnswers,
  assessmentBlueprints,
  assessmentItemOptions,
  assessmentItems,
  assessmentScores,
  assessmentSessions,
  auditLogs,
  contentScenarioOptions,
  contentScenarios,
  credibilityScores,
  decisionLogs,
  revalidationSchedules,
  riskScores,
  tenantSettings,
  userStates,
  users,
} from "../../drizzle/schema";
import { getDb } from "../db";
import { protectedProcedure, router } from "../_core/trpc";
import {
  computeCapabilityScores,
  computeOverallScore,
  computeSignalScores,
  classifyReadiness,
  computeConfidenceProfile,
  detectFailureModes,
} from "../assessment/scoringEngine";
import {
  SessionController,
  MINIMUM_EVIDENCE,
  type AnswerData,
} from "../assessment/sessionController";
import {
  determineSessionPhase,
  generateAdaptiveItem,
  selectNextGenerationVariables,
  DEFAULT_ORG_INTENT,
  TYPES_WITH_AI_OUTPUT,
  TYPES_WITH_DATA,
  type AdaptiveSelectionContext,
  type InteractionType,
  type GeneratedItem,
  type OrgIntent,
} from "../assessment/adaptiveEngine";
import { resolveRoleArchetype } from "../assessment/roleArchetypes";
import { getActiveScoringConfig } from "../assessment/scoringConfig";
import { shouldApplyPersonaAdaptation } from "../assessment/featureFlags";
import { organisationCapabilityThresholds } from "../../drizzle/schema";
import { detectContradictions, generateContradictionProbeSpec, type AnswerRecord } from "../assessment/contradictionEngine";
import { analyseGamingPatterns } from "../assessment/antiGamingEngine";
import { invokeLLM } from "../_core/llm";
import type { CapabilityKey } from "../assessment/roleArchetypes";
// I2: AIL bridge — wire assessment completion into the AIL pipeline
import { processAssessmentThroughAIL } from "../ail/userIntelligenceProfile";
// I10: Persona classification — use persona profile to influence assessment difficulty
import { getPersonaProfile, getPersonaAdaptedParameters } from "../ail/personaClassificationEngine";

// ─── Capability Display + Colour Maps ────────────────────────────────────────

const CAPABILITY_DISPLAY: Record<string, string> = {
  execution:           "AI Execution",
  judgement:           "AI Judgement",
  governance:          "AI Risk & Governance",
  appropriateness:     "AI Appropriateness",
  workflow:            "AI Workflow Application",
  data_interpretation: "AI Data & Insight",
};

const CAPABILITY_COLOURS: Record<string, string> = {
  execution:           "#4477AA",
  judgement:           "#AA3377",
  governance:          "#228833",
  appropriateness:     "#EE6677",
  workflow:            "#CCBB44",
  data_interpretation: "#66CCEE",
};

// ─── NextItem type ────────────────────────────────────────────────────────────

type NextItem = {
  id: string;
  itemType: string;
  prompt: string;
  difficulty: number;
  title: string;
  scenario: string;
  constraint: string;
  question: string;
  /** Present for scenario_critique, output_improvement, error_detection */
  aiOutput?: string;
  /** Present for data_interpretation */
  dataContext?: string;
  capability: string;
  capabilityKey: string;
  workflow: string;
  riskLevel: string;
  interactionType: string;
  interactionId: string;
  primarySignal: string;
  displayOrder: number;
  isGenerated: boolean;
  options: Array<{ id: string; label: string; value: string; optionOrder: number }>;
};

// ─── Helper: Enrich answers with item metadata ────────────────────────────────

async function enrichAnswers(
  answers: Array<{
    id: string;
    itemId: string;
    selectedValueJson: unknown;
    freeText: string | null;
    confidenceScore: unknown;
    timeToAnswerMs: number;
    outcomeClass: string | null;
    signalDeltasJson: unknown;
    eventCodesJson: unknown;
    revisionCount: number;
  }>,
  db: NonNullable<Awaited<ReturnType<typeof getDb>>>
): Promise<AnswerData[]> {
  return Promise.all(
    answers.map(async (a) => {
      let riskLevel = "Medium";
      let capabilityKey = "execution";
      let interactionType = "situational_judgement";
      let itemDifficulty = 2;
      let optionPosition: number | null = null;

      if (a.itemId.startsWith("cs-")) {
        const scenarioId = a.itemId.slice(3);
        const cs = await db
          .select({ difficulty: contentScenarios.difficulty, riskLevel: contentScenarios.riskLevel, capabilityKey: contentScenarios.capabilityKey, interactionType: contentScenarios.interactionType })
          .from(contentScenarios)
          .where(eq(contentScenarios.id, scenarioId))
          .limit(1);
        if (cs[0]) {
          riskLevel = cs[0].riskLevel;
          capabilityKey = cs[0].capabilityKey;
          interactionType = cs[0].interactionType;
          itemDifficulty = cs[0].difficulty;
        }
      } else {
        const item = await db
          .select({ difficulty: assessmentItems.difficulty, metadataJson: assessmentItems.metadataJson })
          .from(assessmentItems)
          .where(eq(assessmentItems.id, a.itemId))
          .limit(1);
        try {
          const meta = (typeof item[0]?.metadataJson === "string"
            ? JSON.parse(item[0].metadataJson as string)
            : (item[0]?.metadataJson ?? {})) as Record<string, unknown>;
          riskLevel = (meta.risk_level as string) ?? "Medium";
          capabilityKey = (meta.capability_key as string) ?? "execution";
          interactionType = (meta.interaction_type as string) ?? "situational_judgement";
          itemDifficulty = item[0]?.difficulty ?? 2;
        } catch {}
      }

      if (a.selectedValueJson) {
        try {
          const selectedVal = typeof a.selectedValueJson === "string"
            ? JSON.parse(a.selectedValueJson as string)
            : a.selectedValueJson;
          const opts = await db
            .select({ value: assessmentItemOptions.value, optionOrder: assessmentItemOptions.optionOrder })
            .from(assessmentItemOptions)
            .where(eq(assessmentItemOptions.itemId, a.itemId));
          const opt = opts.find(o => o.value === selectedVal);
          optionPosition = opt?.optionOrder ?? null;
        } catch {}
      }

      function safeJsonParse(val: unknown): unknown {
        if (val === null || val === undefined) return null;
        if (typeof val !== "string") return val;
        try { return JSON.parse(val); } catch { return val; }
      }

      return {
        itemId: a.itemId,
        selectedValue: a.selectedValueJson ? safeJsonParse(a.selectedValueJson) as string : null,
        freeText: a.freeText ?? undefined,
        confidenceScore: parseFloat(String(a.confidenceScore ?? "0.5")),
        timeToAnswerMs: a.timeToAnswerMs,
        outcomeClass: a.outcomeClass ?? null,
        signalDeltasJson: a.signalDeltasJson ?? {},
        eventCodesJson: a.eventCodesJson ?? [],
        riskLevel,
        difficulty: itemDifficulty,
        capabilityKey,
        interactionType,
        optionPosition,
      };
    })
  );
}

// ─── Helper: Build NextItem from GeneratedItem + persist to DB ────────────────

async function persistAndBuildNextItem(
  generated: GeneratedItem,
  blueprintId: string,
  answeredCount: number,
  phase: string,
  evidenceObjective: string,
  db: NonNullable<Awaited<ReturnType<typeof getDb>>>
): Promise<NextItem> {
  const generatedItemId = `gen-${nanoid()}`;
  const generatedItemMetadata: Record<string, unknown> = {
    title: generated.title,
    scenario: generated.scenario,
    constraint: generated.constraint,
    question: generated.question,
    capability: CAPABILITY_DISPLAY[generated.capabilityKey] ?? generated.capabilityKey,
    capability_key: generated.capabilityKey,
    workflow: generated.workflow,
    risk_level: generated.riskLevel,
    interaction_type: generated.interactionType,
    interaction_id: `gen-${generatedItemId}`,
    primary_signal: evidenceObjective,
    display_order: answeredCount + 1,
    generated: true,
    phase,
  };

  // Store aiOutput and dataContext in metadata for retrieval
  if (generated.aiOutput) generatedItemMetadata["ai_output"] = generated.aiOutput;
  if (generated.dataContext) generatedItemMetadata["data_context"] = generated.dataContext;

  await db.insert(assessmentItems).values({
    id: generatedItemId,
    blueprintId,
    itemType: generated.interactionType,
    prompt: `${generated.scenario}\n\n${generated.constraint}\n\n${generated.question}`,
    metadataJson: generatedItemMetadata,
    difficulty: generated.difficulty,
    status: "published",
  });

  for (let i = 0; i < generated.options.length; i++) {
    const opt = generated.options[i];
    await db.insert(assessmentItemOptions).values({
      id: `${generatedItemId}-opt-${i}`,
      itemId: generatedItemId,
      label: opt.text,
      value: opt.label.toUpperCase(),
      optionOrder: i + 1,
      isCorrect: opt.outcomeClass === "strong",
      scoreWeight: (opt.outcomeClass === "strong" ? 1 : opt.outcomeClass === "acceptable" ? 0.5 : 0) as any,
      outcomeClass: opt.outcomeClass,
      signalDeltasJson: opt.signalDeltas,
      eventCodesJson: opt.eventCodes,
      rationaleText: opt.rationale ?? null,
    });
  }

  return {
    id: generatedItemId,
    itemType: generated.interactionType,
    prompt: `${generated.scenario}\n\n${generated.constraint}\n\n${generated.question}`,
    difficulty: generated.difficulty,
    title: generated.title,
    scenario: generated.scenario,
    constraint: generated.constraint,
    question: generated.question,
    aiOutput: generated.aiOutput,
    dataContext: generated.dataContext,
    capability: CAPABILITY_DISPLAY[generated.capabilityKey] ?? generated.capabilityKey,
    capabilityKey: generated.capabilityKey,
    workflow: generated.workflow,
    riskLevel: generated.riskLevel,
    interactionType: generated.interactionType,
    interactionId: `gen-${generatedItemId}`,
    primarySignal: evidenceObjective,
    displayOrder: answeredCount + 1,
    isGenerated: true,
    options: generated.options.map((opt, i) => ({
      id: `${generatedItemId}-opt-${i}`,
      label: opt.text,
      value: opt.label.toUpperCase(),
      optionOrder: i + 1,
    })),
  };
}

// ─── Helper: Build adaptive context from answers + user profile ───────────────

function buildAdaptiveContext(
  answers: AnswerData[],
  answeredCount: number,
  roleHint: string | null,
  userProfile: {
    sector?: string | null;
    seniority?: string | null;
    aiUsageLevel?: string | null;
    jobFunction?: string | null;
  },
  priorCapabilityScores: Record<string, number> | null,
  // C2.2: Tenant org context loaded from ailOrgContext at session start
  tenantOrgContext?: {
    aiTools?: string[] | null;
    aiAmbition?: string | null;
    strategicPriorities?: string[] | null;
    governanceSensitivity?: "low" | "medium" | "high" | "critical";
  } | null,
  // I4/I5/I6/I7: Session tracking state for adaptive improvements
  sessionMetaForTracking?: Record<string, unknown> | null
): { ctx: AdaptiveSelectionContext; generationVars: ReturnType<typeof selectNextGenerationVariables> } {
  const signalScores = computeSignalScores(
    answers.map(a => ({
      signalDeltasJson: a.signalDeltasJson,
      outcomeClass: a.outcomeClass,
      riskLevel: a.riskLevel,
      difficulty: a.difficulty,
      confidenceScore: a.confidenceScore,
      timeToAnswerMs: a.timeToAnswerMs,
    }))
  );
  const capabilityScores = computeCapabilityScores(signalScores);
  const capabilityScoreSummary = Object.fromEntries(
    Object.entries(capabilityScores).map(([k, v]) => [k, { score: v.score, signalCount: v.signalCount }])
  ) as Record<CapabilityKey, { score: number; signalCount: number }>;

  // B5: Include declaredSeniority from resolved role archetype for seniority-inconsistency detection
  const answerRecords: AnswerRecord[] = answers.map(a => ({
    itemId: a.itemId,
    capabilityKey: a.capabilityKey,
    outcomeClass: a.outcomeClass,
    signalDeltas: (() => {
      try { return typeof a.signalDeltasJson === "string" ? JSON.parse(a.signalDeltasJson) : (a.signalDeltasJson as Record<string, number>) ?? {}; } catch { return {}; }
    })(),
    confidenceScore: a.confidenceScore,
    interactionType: a.interactionType,
    riskLevel: a.riskLevel,
    declaredSeniority: roleArchetype.seniority,
  }));
  const contradictions = detectContradictions(answerRecords);

  const gamingAnswers = answers.map(a => ({
    selectedValue: a.selectedValue,
    optionPosition: a.optionPosition,
    timeToAnswerMs: a.timeToAnswerMs,
    outcomeClass: a.outcomeClass,
    confidenceScore: a.confidenceScore,
    signalDeltas: (() => {
      try { return typeof a.signalDeltasJson === "string" ? JSON.parse(a.signalDeltasJson) : (a.signalDeltasJson as Record<string, number>) ?? {}; } catch { return {}; }
    })(),
    interactionType: a.interactionType,
  }));
  const gamingAnalysis = analyseGamingPatterns(gamingAnswers);

  const riskExposure = {
    Low: answers.filter(a => a.riskLevel === "Low").length,
    Medium: answers.filter(a => a.riskLevel === "Medium").length,
    High: answers.filter(a => a.riskLevel === "High").length,
  };

  const interactionTypesUsed = Object.fromEntries(
    answers.reduce((acc, a) => {
      acc.set(a.interactionType, (acc.get(a.interactionType) ?? 0) + 1);
      return acc;
    }, new Map<string, number>())
  ) as Record<InteractionType, number>;

  const roleArchetype = resolveRoleArchetype(roleHint);

  const ctx: AdaptiveSelectionContext = {
    answeredCount,
    totalTarget: MINIMUM_EVIDENCE.targetItems,
    capabilityScores: capabilityScoreSummary,
    interactionTypesUsed,
    riskExposure,
    gamingAnalysis,
    // B6: Use updated 2-arg signature — capabilityKey is now stored on the pair
    // D3: Respect high-scrutiny probe cap (3 probes when scrutiny is high, 2 otherwise)
    contradictionProbes: contradictions.pairs.slice(0, gamingAnalysis.scrutinyLevel === "high" ? 3 : 2).map(pair =>
      generateContradictionProbeSpec(pair, roleArchetype.id)
    ),
    roleArchetype,
    // C2.2: Use tenant org context if available, otherwise fall back to DEFAULT_ORG_INTENT
    orgIntent: tenantOrgContext ? {
      ...DEFAULT_ORG_INTENT,
      aiAmbition: (tenantOrgContext.aiAmbition as OrgIntent["aiAmbition"]) ?? DEFAULT_ORG_INTENT.aiAmbition,
      governanceSensitivity: tenantOrgContext.governanceSensitivity ?? DEFAULT_ORG_INTENT.governanceSensitivity,
    } : DEFAULT_ORG_INTENT,
    userSector: userProfile.sector,
    userSeniority: userProfile.seniority,
    userAiUsageLevel: userProfile.aiUsageLevel,
    priorCapabilityScores,
    // I4: Cross-session deduplication
    priorSeenStaticItemIds: (sessionMetaForTracking?.priorSeenStaticItemIds as string[]) ?? [],
    // I5/I6/I7: Within-session tracking state
    recentWorkflows: (sessionMetaForTracking?.recentWorkflows as string[]) ?? [],
    consecutiveStrongAnswers: (sessionMetaForTracking?.consecutiveStrongAnswers as number) ?? 0,
    recentCapabilities: (sessionMetaForTracking?.recentCapabilities as CapabilityKey[]) ?? [],
  };

  const generationVars = selectNextGenerationVariables(ctx);
  return { ctx, generationVars };
}

// ─── Helper: Get emergency fallback static item ───────────────────────────────

async function getEmergencyFallbackItem(
  blueprintId: string,
  answeredItemIds: string[],
  answeredCount: number,
  db: NonNullable<Awaited<ReturnType<typeof getDb>>>,
  // I4: Cross-session deduplication — exclude static items seen in prior sessions
  priorSeenStaticItemIds: string[] = []
): Promise<NextItem | null> {
  const allStaticItems = await db
    .select({ id: assessmentItems.id, metadataJson: assessmentItems.metadataJson })
    .from(assessmentItems)
    .where(
      and(
        eq(assessmentItems.blueprintId, blueprintId),
        eq(assessmentItems.status, "published"),
        notLike(assessmentItems.id, "gen-%")
      )
    );
  const allExcluded = new Set([...answeredItemIds, ...priorSeenStaticItemIds]);
  // First try to find items not seen in this session OR prior sessions
  let unanswered = allStaticItems
    .filter(i => !allExcluded.has(i.id));
  // If all items have been seen across sessions, fall back to only excluding current-session items
  if (unanswered.length === 0) {
    unanswered = allStaticItems.filter(i => !answeredItemIds.includes(i.id));
  }
  unanswered.sort((a, b) => {
      let ma: Record<string, unknown> = {}, mb: Record<string, unknown> = {};
      try { ma = (typeof a.metadataJson === "string" ? JSON.parse(a.metadataJson as string) : (a.metadataJson ?? {})) as Record<string, unknown>; } catch {}
      try { mb = (typeof b.metadataJson === "string" ? JSON.parse(b.metadataJson as string) : (b.metadataJson ?? {})) as Record<string, unknown>; } catch {}
      return ((ma.display_order as number) ?? 999) - ((mb.display_order as number) ?? 999);
    });
  if (unanswered.length === 0) return null;
  const nextItemFull = await db
    .select()
    .from(assessmentItems)
    .where(eq(assessmentItems.id, unanswered[0].id))
    .limit(1);
  if (!nextItemFull[0]) return null;
  const options = await db
    .select()
    .from(assessmentItemOptions)
    .where(eq(assessmentItemOptions.itemId, nextItemFull[0].id))
    .orderBy(assessmentItemOptions.optionOrder);
  let meta: Record<string, unknown> = {};
  try { meta = (typeof nextItemFull[0].metadataJson === "string" ? JSON.parse(nextItemFull[0].metadataJson as string) : (nextItemFull[0].metadataJson ?? {})) as Record<string, unknown>; } catch {}
  return {
    id: nextItemFull[0].id,
    itemType: nextItemFull[0].itemType,
    prompt: nextItemFull[0].prompt,
    difficulty: nextItemFull[0].difficulty,
    title: (meta.title as string) ?? "",
    scenario: (meta.scenario as string) ?? "",
    constraint: (meta.constraint as string) ?? "",
    question: (meta.question as string) ?? "What is the most appropriate action?",
    aiOutput: (meta.ai_output as string) ?? undefined,
    dataContext: (meta.data_context as string) ?? undefined,
    capability: (meta.capability as string) ?? "",
    capabilityKey: (meta.capability_key as string) ?? "execution",
    workflow: (meta.workflow as string) ?? "",
    riskLevel: (meta.risk_level as string) ?? "Medium",
    interactionType: (meta.interaction_type as string) ?? "situational_judgement",
    interactionId: (meta.interaction_id as string) ?? "",
    primarySignal: (meta.primary_signal as string) ?? "",
    displayOrder: (meta.display_order as number) ?? answeredCount + 1,
    isGenerated: false,
    options: options.map(({ isCorrect: _ic, scoreWeight: _sw, signalDeltasJson: _sd, eventCodesJson: _ec, outcomeClass: _oc, ...o }) => o),
  };
}

// ─── Router ───────────────────────────────────────────────────────────────────

export const assessmentRouter = router({
  // ── List published blueprints ──────────────────────────────────────────────
  blueprints: protectedProcedure.query(async () => {
    const db = await getDb();
    if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR" });
    return db
      .select()
      .from(assessmentBlueprints)
      .where(eq(assessmentBlueprints.status, "published"));
  }),

  // ── Get default blueprint ──────────────────────────────────────────────────
  defaultBlueprint: protectedProcedure.query(async () => {
    const db = await getDb();
    if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR" });
    const bps = await db
      .select()
      .from(assessmentBlueprints)
      .where(eq(assessmentBlueprints.status, "published"))
      .orderBy(desc(assessmentBlueprints.createdAt))
      .limit(5);
    const v9 = bps.find(b => b.key === "aiq_v9_standard");
    const bp = v9 ?? bps[0] ?? null;
    if (!bp) return null;
    const items = await db
      .select({ id: assessmentItems.id })
      .from(assessmentItems)
      .where(
        and(
          eq(assessmentItems.blueprintId, bp.id),
          eq(assessmentItems.status, "published")
        )
      );
    return { ...bp, itemCount: items.length };
  }),

  // ── Get blueprint with items ───────────────────────────────────────────────
  blueprint: protectedProcedure
    .input(z.object({ blueprintId: z.string() }))
    .query(async ({ input }) => {
      const db = await getDb();
      if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR" });
      const bp = await db
        .select()
        .from(assessmentBlueprints)
        .where(eq(assessmentBlueprints.id, input.blueprintId))
        .limit(1);
      if (!bp[0]) throw new TRPCError({ code: "NOT_FOUND" });
      const items = await db
        .select()
        .from(assessmentItems)
        .where(
          and(
            eq(assessmentItems.blueprintId, input.blueprintId),
            eq(assessmentItems.status, "published")
          )
        );
      const itemsWithOptions = await Promise.all(
        items.map(async item => {
          const options = await db
            .select()
            .from(assessmentItemOptions)
            .where(eq(assessmentItemOptions.itemId, item.id))
            .orderBy(assessmentItemOptions.optionOrder);
          return {
            ...item,
            options: options.map(({ isCorrect, scoreWeight, signalDeltasJson, eventCodesJson, outcomeClass, ...o }) => o),
          };
        })
      );
      return { ...bp[0], items: itemsWithOptions };
    }),

  // ── Start or resume a session ──────────────────────────────────────────────
  startSession: protectedProcedure
    .input(z.object({
      blueprintId: z.string(),
      roleHint: z.string().optional(),
    }))
    .mutation(async ({ input, ctx }) => {
      const db = await getDb();
      if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR" });

      // Resume existing in-progress session
      const existing = await db
        .select()
        .from(assessmentSessions)
        .where(
          and(
            eq(assessmentSessions.userId, ctx.user.id),
            eq(assessmentSessions.blueprintId, input.blueprintId),
            eq(assessmentSessions.state, "in_progress")
          )
        )
        .limit(1);
      if (existing[0]) return { sessionId: existing[0].id, resumed: true };

      // Validate blueprint exists
      const blueprint = await db
        .select({ id: assessmentBlueprints.id })
        .from(assessmentBlueprints)
        .where(eq(assessmentBlueprints.id, input.blueprintId))
        .limit(1);
      if (!blueprint[0]) {
        throw new TRPCError({ code: "NOT_FOUND", message: `Blueprint '${input.blueprintId}' not found` });
      }

      // Check if this is the user's first assessment (baseline flag)
      const priorSessions = await db
        .select({ id: assessmentSessions.id })
        .from(assessmentSessions)
        .where(
          and(
            eq(assessmentSessions.userId, ctx.user.id),
            eq(assessmentSessions.state, "completed")
          )
        )
        .limit(1);
      const isBaseline = priorSessions.length === 0;

      // Fetch prior capability scores for adaptive calibration
      // S9: Only apply if persona adaptation feature flag is enabled AND user has sufficient history
      let priorCapabilityScores: Record<string, number> | null = null;
      const priorSessionCount = priorSessions.length;
      const personaAdaptationActive = shouldApplyPersonaAdaptation(priorSessionCount);
      if (!isBaseline && personaAdaptationActive) {
        const priorScore = await db
          .select({ scoreBreakdownJson: assessmentScores.scoreBreakdownJson })
          .from(assessmentScores)
          .innerJoin(assessmentSessions, eq(assessmentSessions.id, assessmentScores.sessionId))
          .where(
            and(
              eq(assessmentSessions.userId, ctx.user.id),
              eq(assessmentSessions.state, "completed")
            )
          )
          .orderBy(desc(assessmentScores.generatedAt))
          .limit(1);
        if (priorScore[0]) {
          try {
            const bd = (typeof priorScore[0].scoreBreakdownJson === "string"
              ? JSON.parse(priorScore[0].scoreBreakdownJson as string)
              : (priorScore[0].scoreBreakdownJson ?? {})) as Record<string, unknown>;
            priorCapabilityScores = (bd.capabilityScores as Record<string, number>) ?? null;
          } catch {}
        }
      }

      // I4: Cross-session deduplication — load static item IDs seen in prior sessions
      let priorSeenStaticItemIds: string[] = [];
      if (priorSessions.length > 0) {
        const priorSessionIds = priorSessions.map(s => s.id);
        try {
          const priorAnswers = await db
            .select({ itemId: assessmentAnswers.itemId })
            .from(assessmentAnswers)
            .where(
              and(
                ...priorSessionIds.map(sid => eq(assessmentAnswers.sessionId, sid))
              )
            );
          // Only deduplicate static items (not LLM-generated ones which start with gen-)
          priorSeenStaticItemIds = Array.from(new Set(
            priorAnswers
              .map(a => a.itemId)
              .filter(id => !id.startsWith("gen-") && !id.startsWith("cs-"))
          ));
        } catch {}
      }
      // I10: Persona-adapted difficulty — load persona profile and use it to influence starting difficulty
      let personaStartingDifficulty: 1 | 2 | 3 = 1;
      let personaTimePressure = false;
      if (personaAdaptationActive) {
        try {
          const personaProfile = await getPersonaProfile(ctx.user.id);
          if (personaProfile && personaProfile.primaryPersona !== "unclassified") {
            const adapted = getPersonaAdaptedParameters(personaProfile.primaryPersona);
            // Map persona time pressure to starting difficulty
            personaStartingDifficulty = adapted.timePressure === "high" ? 2 : 1;
            personaTimePressure = adapted.timePressure !== "low";
          }
        } catch {}
      }
      const sessionId = nanoid();
      await db.insert(assessmentSessions).values({
        id: sessionId,
        tenantId: ctx.user.tenantId,
        userId: ctx.user.id,
        blueprintId: input.blueprintId,
        state: "in_progress",
        startedAt: new Date(),
        sessionMetadataJson: {
          blueprintId: input.blueprintId,
          roleHint: input.roleHint ?? null,
          engineVersion: "adaptive-v2",
          isBaseline,
          priorCapabilityScores,
          // S9: Record whether persona adaptation was active for this session
          personaAdaptationActive,
          // I4: Cross-session deduplication
          priorSeenStaticItemIds,
          // I10: Persona-adapted starting difficulty
          personaStartingDifficulty,
          personaTimePressure,
          // I6/I7: Tracking state for within-session difficulty escalation and over-probe guard
          consecutiveStrongAnswers: 0,
          recentCapabilities: [] as string[],
          recentWorkflows: [] as string[],
          pendingNextItem: null,
        },
      });

      await db.insert(auditLogs).values({
        id: nanoid(),
        tenantId: ctx.user.tenantId,
        actorUserId: ctx.user.id,
        action: "assessment.session.started",
        targetType: "assessment_session",
        targetId: sessionId,
        metadataJson: JSON.stringify({ blueprintId: input.blueprintId, engineVersion: "adaptive-v2", isBaseline }),
      });

      return { sessionId, resumed: false };
    }),

  // ── Get session state + next item (adaptive, LLM-first) ───────────────────
  session: protectedProcedure
    .input(z.object({ sessionId: z.string() }))
    .query(async ({ input, ctx }) => {
      const db = await getDb();
      if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR" });

      const session = await db
        .select()
        .from(assessmentSessions)
        .where(
          and(
            eq(assessmentSessions.id, input.sessionId),
            eq(assessmentSessions.userId, ctx.user.id)
          )
        )
        .limit(1);
      if (!session[0]) throw new TRPCError({ code: "NOT_FOUND" });

      const rawAnswers = await db
        .select()
        .from(assessmentAnswers)
        .where(eq(assessmentAnswers.sessionId, input.sessionId));

      const answers = await enrichAnswers(rawAnswers, db);
      const answeredCount = answers.length;
      const answeredItemIds = rawAnswers.map(a => a.itemId);

      // Parse session metadata
      let meta: Record<string, unknown> = {};
      try {
        meta = (typeof session[0].sessionMetadataJson === "string"
          ? JSON.parse(session[0].sessionMetadataJson as string)
          : (session[0].sessionMetadataJson ?? {})) as Record<string, unknown>;
      } catch {}

      const roleHint = (meta.roleHint as string) ?? null;
      const priorCapabilityScores = (meta.priorCapabilityScores as Record<string, number>) ?? null;

      // Fetch user profile for personalisation
      const userRow = await db
        .select({
          sector: users.sector,
          seniorityLevel: users.seniorityLevel,
          aiUsageLevel: users.aiUsageLevel,
          jobFunction: users.jobFunction,
        })
        .from(users)
        .where(eq(users.id, ctx.user.id))
        .limit(1);
      const userProfile = {
        sector: userRow[0]?.sector ?? null,
        seniority: userRow[0]?.seniorityLevel ?? null,
        aiUsageLevel: userRow[0]?.aiUsageLevel ?? null,
        jobFunction: userRow[0]?.jobFunction ?? null,
      };

      const phase = determineSessionPhase(answeredCount, MINIMUM_EVIDENCE.targetItems);
      // D2: Pass roleHint into computeState so role-specific evidence thresholds are applied
      const state = SessionController.computeState(
        session[0].id,
        ctx.user.id,
        session[0].blueprintId,
        answers,
        MINIMUM_EVIDENCE.targetItems,
        roleHint
      );

       let nextItem: NextItem | null = null;
      // T1-3: Generate next item when in_progress AND not yet at target items
      // AND evidence is not yet sufficient (early completion will handle that case)
      const shouldGenerateNextItem = session[0].state === "in_progress" &&
        answeredCount < MINIMUM_EVIDENCE.targetItems &&
        !state.evidenceSufficient;
      if (shouldGenerateNextItem) {
        // ── Step 1: Check for pre-generated pending item (zero latency) ────────
        const pendingNextItem = meta.pendingNextItem as NextItem | null;
        if (pendingNextItem && pendingNextItem.id && !answeredItemIds.includes(pendingNextItem.id)) {
          nextItem = pendingNextItem;
        }

        // ── Step 2: Generate item via LLM (primary path) ──────────────────────
        if (!nextItem) {
          try {
            // C2.3: Load tenant org context to replace DEFAULT_ORG_INTENT
            const orgContextRow = await db
              .select({
                currentAiToolsJson: ailOrgContext.currentAiToolsJson,
                aiMaturityLevel: ailOrgContext.aiMaturityLevel,
                strategicPrioritiesJson: ailOrgContext.strategicPrioritiesJson,
                riskAppetiteOverall: ailOrgContext.riskAppetiteOverall,
              })
              .from(ailOrgContext)
              .where(eq(ailOrgContext.tenantId, ctx.user.tenantId))
              .limit(1);
            const orgCtx = orgContextRow[0] ? {
              aiTools: (() => { try { return JSON.parse(orgContextRow[0].currentAiToolsJson ?? "[]") as string[]; } catch { return null; } })(),
              aiAmbition: orgContextRow[0].aiMaturityLevel === "mature" ? "ambitious" : orgContextRow[0].aiMaturityLevel === "cautious" ? "conservative" : "moderate",
              strategicPriorities: (() => { try { return JSON.parse(orgContextRow[0].strategicPrioritiesJson ?? "[]") as string[]; } catch { return null; } })(),
              governanceSensitivity: (orgContextRow[0].riskAppetiteOverall === "risk_averse" ? "critical" : orgContextRow[0].riskAppetiteOverall === "risk_tolerant" ? "medium" : "high") as "low" | "medium" | "high" | "critical",
            } : null;
            const { generationVars } = buildAdaptiveContext(
              answers,
              answeredCount,
              roleHint,
              userProfile,
              priorCapabilityScores,
              orgCtx,
              meta // I4/I5/I6/I7: pass session tracking state
            );
            // C2.2: Pass org context fields into generation vars for LLM prompt
            if (orgCtx) {
              (generationVars as any).orgAiTools = orgCtx.aiTools;
              (generationVars as any).orgAiAmbition = orgCtx.aiAmbition;
              (generationVars as any).orgStrategicPriorities = orgCtx.strategicPriorities;
            }
            const generated = await generateAdaptiveItem(generationVars);
            nextItem = await persistAndBuildNextItem(
              generated,
              session[0].blueprintId,
              answeredCount,
              phase,
              generationVars.evidenceObjective,
              db
            );
          } catch (err) {
            console.error("[assessment.session] LLM generation failed, using fallback:", err);
          }
        }

        // ── Step 3: Emergency fallback — static item ──────────────────────────
        if (!nextItem) {
          // I4: Pass prior-session seen items to avoid repeating static items
          const priorSeenIds = (meta.priorSeenStaticItemIds as string[]) ?? [];
          nextItem = await getEmergencyFallbackItem(
            session[0].blueprintId,
            answeredItemIds,
            answeredCount,
            db,
            priorSeenIds
          );
        }
      }

      // T1-2: Early completion — allow completion once evidence is sufficient,
      // even before all targetItems are answered (minimum 20 items required)
      const isComplete = session[0].state !== "in_progress" ||
        (answeredCount >= MINIMUM_EVIDENCE.targetItems && !nextItem) ||
        (state.evidenceSufficient && answeredCount >= MINIMUM_EVIDENCE.totalItems);

      return {
        session: session[0],
        answers: rawAnswers,
        totalItems: MINIMUM_EVIDENCE.targetItems,
        answeredCount,
        nextItem,
        isComplete,
        phase,
        sessionState: {
          canComplete: state.canComplete,
          completionBlockers: state.completionBlockers,
          evidenceSufficient: state.evidenceSufficient,
          interactionTypesUsed: state.interactionTypesUsed,
          contradictionCount: state.contradictionCount,
          gamingScrutinyLevel: state.gamingScrutinyLevel,
        },
      };
    }),

  // ── Submit an answer + trigger async pre-generation of next item ──────────
  submitAnswer: protectedProcedure
    .input(
      z.object({
        sessionId: z.string(),
        itemId: z.string(),
        selectedValue: z.string().nullable(),
        freeText: z.string().optional(),
        // C2.1: Optional reasoning capture — participant's explanation of their thinking
        // Shown for judgement/governance/critique item types; max 2000 chars
        reasoningText: z.string().max(2000).optional(),
        confidenceScore: z.number().min(0).max(1).optional(),
        timeToAnswerMs: z.number().int().min(0),
      })
    )
    .mutation(async ({ input, ctx }) => {
      const db = await getDb();
      if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR" });

      const session = await db
        .select()
        .from(assessmentSessions)
        .where(
          and(
            eq(assessmentSessions.id, input.sessionId),
            eq(assessmentSessions.userId, ctx.user.id),
            eq(assessmentSessions.state, "in_progress")
          )
        )
        .limit(1);
      if (!session[0]) throw new TRPCError({ code: "NOT_FOUND", message: "Active session not found" });

      // Resolve outcome from selected option
      let correctness: boolean | null = null;
      let outcomeClass: string | null = null;
      let signalDeltasJson: unknown = null;
      let eventCodesJson: unknown = null;
      let rationaleText: string | null = null;
      // Also fetch all options so we can return rationale for all choices
      let allOptionsRationale: Array<{ value: string; rationaleText: string | null; outcomeClass: string | null }> = [];
      if (input.selectedValue) {
        const options = await db
          .select()
          .from(assessmentItemOptions)
          .where(eq(assessmentItemOptions.itemId, input.itemId));
        allOptionsRationale = options.map(o => ({
          value: o.value,
          rationaleText: o.rationaleText ?? null,
          outcomeClass: o.outcomeClass ?? null,
        }));
        const selected = options.find(o => o.value === input.selectedValue);
        if (selected) {
          correctness = selected.isCorrect ?? null;
          outcomeClass = selected.outcomeClass ?? null;
          signalDeltasJson = selected.signalDeltasJson ?? null;
          eventCodesJson = selected.eventCodesJson ?? null;
          rationaleText = selected.rationaleText ?? null;
        }
      }
      // Save answer
      await db.insert(assessmentAnswers).values({
        id: nanoid(),
        sessionId: input.sessionId,
        itemId: input.itemId,
        selectedValueJson: input.selectedValue ? JSON.stringify(input.selectedValue) : null,
        freeText: input.freeText ?? null,
        reasoningText: input.reasoningText ?? null, // C2.1: reasoning capture
        confidenceScore: input.confidenceScore?.toFixed(4) as any,
        timeToAnswerMs: input.timeToAnswerMs,
        correctness,
        outcomeClass: outcomeClass as any,
        signalDeltasJson,
        eventCodesJson,
      });

      // ── Async pre-generation: generate next item in the background ──────────
      // This runs after the answer is saved so the user gets an instant response.
      // The generated item is stored in session_metadata_json.pendingNextItem.
      // On the next session query, it's served instantly with zero LLM latency.
      const newAnsweredCount = (await db
        .select()
        .from(assessmentAnswers)
        .where(eq(assessmentAnswers.sessionId, input.sessionId))).length;

      if (newAnsweredCount < MINIMUM_EVIDENCE.targetItems) {
        // Fire-and-forget: do not await, do not block the response
        (async () => {
          try {
            const rawAnswers = await db
              .select()
              .from(assessmentAnswers)
              .where(eq(assessmentAnswers.sessionId, input.sessionId));
            const answers = await enrichAnswers(rawAnswers, db);
            const answeredItemIds = rawAnswers.map(a => a.itemId);

            let sessionMeta: Record<string, unknown> = {};
            try {
              sessionMeta = (typeof session[0].sessionMetadataJson === "string"
                ? JSON.parse(session[0].sessionMetadataJson as string)
                : (session[0].sessionMetadataJson ?? {})) as Record<string, unknown>;
            } catch {}

            const roleHint = (sessionMeta.roleHint as string) ?? null;
            const priorCapabilityScores = (sessionMeta.priorCapabilityScores as Record<string, number>) ?? null;

            const userRow = await db
              .select({
                sector: users.sector,
                seniorityLevel: users.seniorityLevel,
                aiUsageLevel: users.aiUsageLevel,
                jobFunction: users.jobFunction,
              })
              .from(users)
              .where(eq(users.id, ctx.user.id))
              .limit(1);
            const userProfile = {
              sector: userRow[0]?.sector ?? null,
              seniority: userRow[0]?.seniorityLevel ?? null,
              aiUsageLevel: userRow[0]?.aiUsageLevel ?? null,
              jobFunction: userRow[0]?.jobFunction ?? null,
            };

            const phase = determineSessionPhase(newAnsweredCount, MINIMUM_EVIDENCE.targetItems);
            // C2.3: Load tenant org context for pre-generation
            const preGenOrgContextRow = await db
              .select({
                currentAiToolsJson: ailOrgContext.currentAiToolsJson,
                aiMaturityLevel: ailOrgContext.aiMaturityLevel,
                strategicPrioritiesJson: ailOrgContext.strategicPrioritiesJson,
                riskAppetiteOverall: ailOrgContext.riskAppetiteOverall,
              })
              .from(ailOrgContext)
              .where(eq(ailOrgContext.tenantId, ctx.user.tenantId))
              .limit(1);
            const preGenOrgCtx = preGenOrgContextRow[0] ? {
              aiTools: (() => { try { return JSON.parse(preGenOrgContextRow[0].currentAiToolsJson ?? "[]") as string[]; } catch { return null; } })(),
              aiAmbition: preGenOrgContextRow[0].aiMaturityLevel === "mature" ? "ambitious" : preGenOrgContextRow[0].aiMaturityLevel === "cautious" ? "conservative" : "moderate",
              strategicPriorities: (() => { try { return JSON.parse(preGenOrgContextRow[0].strategicPrioritiesJson ?? "[]") as string[]; } catch { return null; } })(),
              governanceSensitivity: (preGenOrgContextRow[0].riskAppetiteOverall === "risk_averse" ? "critical" : preGenOrgContextRow[0].riskAppetiteOverall === "risk_tolerant" ? "medium" : "high") as "low" | "medium" | "high" | "critical",
            } : null;
              const { generationVars, ctx: adaptiveCtx } = buildAdaptiveContext(
              answers,
              newAnsweredCount,
              roleHint,
              userProfile,
              priorCapabilityScores,
              preGenOrgCtx,
              sessionMeta // I4/I5/I6/I7: pass session tracking state
            );
            if (preGenOrgCtx) {
              (generationVars as any).orgAiTools = preGenOrgCtx.aiTools;
              (generationVars as any).orgAiAmbition = preGenOrgCtx.aiAmbition;
              (generationVars as any).orgStrategicPriorities = preGenOrgCtx.strategicPriorities;
            }
            const generated = await generateAdaptiveItem(generationVars);
            const pendingItem = await persistAndBuildNextItem(
              generated,
              session[0].blueprintId,
              newAnsweredCount,
              phase,
              generationVars.evidenceObjective,
              db
            );
            // I6/I7: Update within-session tracking state
            const lastAnswer = answers[answers.length - 1];
            const lastOutcome = lastAnswer?.outcomeClass ?? null;
            const prevConsecutive = (sessionMeta.consecutiveStrongAnswers as number) ?? 0;
            const newConsecutive = lastOutcome === "strong" ? prevConsecutive + 1 : 0;
            const prevRecentCaps = (sessionMeta.recentCapabilities as string[]) ?? [];
            const newRecentCaps = [...prevRecentCaps.slice(-4), generationVars.targetCapability];
            const prevRecentWorkflows = (sessionMeta.recentWorkflows as string[]) ?? [];
            const newRecentWorkflows = [...prevRecentWorkflows.slice(-4), generationVars.workflowContext];
            // Store the pre-generated item and updated tracking state in session metadata
            await db
              .update(assessmentSessions)
              .set({
                sessionMetadataJson: {
                  ...sessionMeta,
                  pendingNextItem: pendingItem,
                  consecutiveStrongAnswers: newConsecutive,
                  recentCapabilities: newRecentCaps,
                  recentWorkflows: newRecentWorkflows,
                },
              })
              .where(eq(assessmentSessions.id, input.sessionId));
            void adaptiveCtx; // suppress unused warning
          } catch (err) {
            console.error("[assessment.submitAnswer] Pre-generation failed (non-fatal):", err);
          }
        })();
      }

      // Compute isComplete so the frontend can show "Complete Assessment" after the last rationale (UX-7)
      const allAnswersFinal = await db
        .select({ id: assessmentAnswers.id })
        .from(assessmentAnswers)
        .where(eq(assessmentAnswers.sessionId, input.sessionId));
      const isCompleteNow = allAnswersFinal.length >= MINIMUM_EVIDENCE.targetItems;
      return { success: true, correctness, outcomeClass, rationaleText, allOptionsRationale, isComplete: isCompleteNow };
    }),

  // ── Complete session and compute full adaptive scores ──────────────────────
  completeSession: protectedProcedure
    .input(z.object({ sessionId: z.string() }))
    .mutation(async ({ input, ctx }) => {
      const db = await getDb();
      if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR" });

      const session = await db
        .select()
        .from(assessmentSessions)
        .where(
          and(
            eq(assessmentSessions.id, input.sessionId),
            eq(assessmentSessions.userId, ctx.user.id),
            eq(assessmentSessions.state, "in_progress")
          )
        )
        .limit(1);
      if (!session[0]) throw new TRPCError({ code: "NOT_FOUND" });

      const rawAnswers = await db
        .select()
        .from(assessmentAnswers)
        .where(eq(assessmentAnswers.sessionId, input.sessionId));

      const answers = await enrichAnswers(rawAnswers, db);

      let roleHint: string | null = null;
      try {
        const meta = (typeof session[0].sessionMetadataJson === "string"
          ? JSON.parse(session[0].sessionMetadataJson as string)
          : (session[0].sessionMetadataJson ?? {})) as Record<string, unknown>;
        roleHint = (meta.roleHint as string) ?? null;
      } catch {}

      // S1: Load active scoring config version
      const activeScoringCfg = await getActiveScoringConfig();

      // S10: Load org-level capability threshold overrides
      let orgThresholdOverrides: Partial<Record<string, number>> | undefined;
      try {
        const roleArchetypeForThresholds = resolveRoleArchetype(roleHint);
        const orgThresholds = await db
          .select()
          .from(organisationCapabilityThresholds)
          .where(
            and(
              eq(organisationCapabilityThresholds.orgId, ctx.user.tenantId),
              eq(organisationCapabilityThresholds.archetypeId, roleArchetypeForThresholds.id)
            )
          );
        if (orgThresholds.length > 0) {
          orgThresholdOverrides = {};
          for (const row of orgThresholds) {
            orgThresholdOverrides[row.capability] = row.minimumSafeThreshold;
          }
        }
      } catch { /* non-fatal */ }

      // S4: Compute reasoning completeness for confidence profile
      // Count items with reasoning_required=true and check if reasoningText was provided
      let reasoningCompleteness = 1.0;
      try {
        const requiredReasoningItems = await db
          .select({ id: assessmentItems.id })
          .from(assessmentItems)
          .where(eq(assessmentItems.reasoningRequired, true));
        const requiredIds = new Set(requiredReasoningItems.map(r => r.id));
        if (requiredIds.size > 0) {
          const answersForRequired = rawAnswers.filter(a => requiredIds.has(a.itemId));
          const adequateReasoning = answersForRequired.filter(
            a => a.reasoningText && a.reasoningText.length >= 40
          ).length;
          reasoningCompleteness = answersForRequired.length > 0
            ? adequateReasoning / answersForRequired.length
            : 1.0;
        }
      } catch { /* non-fatal */ }

      const results = SessionController.computeResults(answers, roleHint, activeScoringCfg, orgThresholdOverrides as any, reasoningCompleteness);

      // R9: Generate LLM-powered personalised development narrative
      let llmNarrative: { strengths: string; gaps: string; priorities: string } | null = null;
      try {
        const capSummary = Object.entries(results.capabilityScores)
          .map(([k, v]) => `${k}: ${Math.round(v.score)}/100`)
          .join(", ");
        const topStrengths = Object.entries(results.capabilityScores)
          .sort((a, b) => b[1].score - a[1].score)
          .slice(0, 2)
          .map(([k]) => k.replace(/_/g, " "))
          .join(" and ");
        const topGaps = Object.entries(results.capabilityScores)
          .sort((a, b) => a[1].score - b[1].score)
          .slice(0, 2)
          .map(([k]) => k.replace(/_/g, " "))
          .join(" and ");
        const roleArchetypeName = results.roleArchetype?.displayName ?? "HR professional";
        const readinessLabel = results.readiness.state;

        const narrativeResp = await invokeLLM({
          messages: [
            {
              role: "system",
              content: `You are an expert AI capability coach writing personalised assessment feedback for HR professionals. 
Write in a professional, direct, and encouraging tone. Be specific — reference the actual capability scores provided. 
Do NOT use bullet points or headers. Write in flowing prose. Each paragraph should be 2-4 sentences.`,
            },
            {
              role: "user",
              content: `Write a 3-paragraph development narrative for a ${roleArchetypeName} who just completed an AI capability assessment.

Assessment results:
- Overall score: ${Math.round(results.overallScore)}/100
- Readiness state: ${readinessLabel}
- Capability scores: ${capSummary}
- Key strengths: ${topStrengths}
- Key gaps: ${topGaps}
- Governance flag: ${results.failureModes.governanceFlag ? "Yes — governance concerns detected" : "No"}
- Over-reliance risk: ${results.failureModes.modes.includes("over_reliance") ? "Yes" : "No"}

Paragraph 1 (Strengths): What this person does well in their AI capability profile. Reference specific capabilities.
Paragraph 2 (Gaps): Where the most significant development opportunities lie. Be honest but constructive.
Paragraph 3 (Priorities): The 2-3 most important actions they should take to improve their AI readiness in their role.

Return ONLY a JSON object with keys: "strengths", "gaps", "priorities" — each containing one paragraph of plain prose text.`,
            },
          ],
          response_format: {
            type: "json_schema",
            json_schema: {
              name: "development_narrative",
              strict: true,
              schema: {
                type: "object",
                properties: {
                  strengths: { type: "string" },
                  gaps: { type: "string" },
                  priorities: { type: "string" },
                },
                required: ["strengths", "gaps", "priorities"],
                additionalProperties: false,
              },
            },
          },
        });
        const narrativeContent = narrativeResp.choices?.[0]?.message?.content;
        if (narrativeContent) {
          const parsed = typeof narrativeContent === "string" ? JSON.parse(narrativeContent) : narrativeContent;
          llmNarrative = {
            strengths: parsed.strengths ?? "",
            gaps: parsed.gaps ?? "",
            priorities: parsed.priorities ?? "",
          };
        }
      } catch (narrativeErr) {
        // Non-fatal — fall back to rule-based narrative from SessionController
        console.warn("[assessment] R9: LLM narrative generation failed, using rule-based fallback:", narrativeErr);
      }

      const capabilityScoresFlat: Record<string, number> = {};
      for (const [key, val] of Object.entries(results.capabilityScores)) {
        capabilityScoresFlat[key] = val.score;
      }

      const scoreBreakdown = {
        overallScore: results.overallScore,
        capabilityScores: capabilityScoresFlat,
        signalScores: results.signalScores,
        readiness: results.readiness,
        narrative: results.narrative,
        confidenceProfile: results.confidenceProfile,
        failureModes: results.failureModes,
        contradictions: {
          count: results.contradictions.count,
          pairs: results.contradictions.pairs,
        },
        contradictionProfile: {
          detected: results.contradictions.count,
          pairs: results.contradictions.pairs.map((p: any) => ({
            itemA: p.itemAId,
            itemB: p.itemBId,
            description: p.description ?? "Inconsistent responses detected between two related items.",
          })),
        },
        governanceProfile: {
          score: results.failureModes.governanceFlag
            ? 30
            : Math.round((results.capabilityScores["governance" as CapabilityKey]?.score ?? 70)),
          band: results.failureModes.governanceFlag
            ? "critical"
            : (results.capabilityScores["governance" as CapabilityKey]?.score ?? 70) >= 75
              ? "strong"
              : "developing",
          bypasses: results.failureModes.governanceFlag ? 1 : 0,
        },
        credibilityBand: results.confidenceProfile.overall >= 0.75 ? "high" : results.confidenceProfile.overall >= 0.5 ? "medium" : "low",
        gamingAnalysis: {
          score: results.gamingAnalysis.score,
          scrutinyLevel: results.gamingAnalysis.scrutinyLevel,
          patterns: results.gamingAnalysis.patterns,
        },
        roleArchetype: results.roleArchetype.id,
        totalAnswers: results.totalAnswers,
        avgConfidence: results.avgConfidence,
        riskBand: results.riskBand,
        modelVersion: "adaptive-v2",
        // R9: LLM-generated personalised development narrative (null if generation failed)
        llmNarrative: llmNarrative ?? null,
        // F3/F4: Percentile ranks, norm group version, and classification confidence gate
        percentileRanks: results.percentileRanks,
        normGroupVersion: results.normGroupVersion,
        classificationConfidence: {
          band: results.confidenceGate.confidenceBand.band,
          label: results.confidenceGate.confidenceBand.label,
          wasDowngraded: results.confidenceGate.wasDowngraded,
          caveat: results.confidenceGate.caveat,
        },
        targetItems: 49,
      };

      await db.insert(assessmentScores).values({
        id: nanoid(),
        sessionId: input.sessionId,
        overallScore: results.overallScore.toFixed(2) as any,
        scoreBreakdownJson: JSON.stringify(scoreBreakdown),
        signalScoresJson: JSON.stringify(results.signalScores),
        modelVersion: "adaptive-v2",
        // S1: stamp the scoring config version used for this result
        scoringConfigVersion: activeScoringCfg.version,
      });

      const credibilityScore = results.confidenceProfile.overall;
      const credibilityBand: "low" | "medium" | "high" =
        credibilityScore >= 0.75 ? "high" : credibilityScore >= 0.5 ? "medium" : "low";
      await db.insert(credibilityScores).values({
        id: nanoid(),
        userId: ctx.user.id,
        assessmentSessionId: input.sessionId,
        credibilityScore: credibilityScore.toFixed(4) as any,
        band: credibilityBand,
        reasonJson: JSON.stringify(results.confidenceProfile),
        modelVersion: "adaptive-v2",
      });

      const riskScore = results.riskBand === "high" ? 0.8 : results.riskBand === "medium" ? 0.5 : 0.2;
      await db.insert(riskScores).values({
        id: nanoid(),
        userId: ctx.user.id,
        riskScore: riskScore.toFixed(4) as any,
        band: results.riskBand,
        reasonJson: JSON.stringify({ failureModes: results.failureModes, contradictions: results.contradictions.count }),
        modelVersion: "adaptive-v2",
      });

      await db
        .update(userStates)
        .set({ effectiveTo: new Date() })
        .where(and(eq(userStates.userId, ctx.user.id), isNull(userStates.effectiveTo)));
      await db.insert(userStates).values({
        id: nanoid(),
        userId: ctx.user.id,
        primaryState: results.readiness.state as any,
        credibilityState: credibilityBand,
        riskState: results.riskBand,
        learningState: results.overallScore >= 70 ? "completed" : "in_progress",
        complianceState: results.failureModes.governanceFlag ? "at_risk" : "compliant",
        stateReasonJson: JSON.stringify({
          source: "assessment",
          sessionId: input.sessionId,
          capabilityScores: capabilityScoresFlat,
          signalScores: results.signalScores,
          modelVersion: "adaptive-v2",
        }),
      });

      await db.insert(decisionLogs).values({
        id: nanoid(),
        tenantId: ctx.user.tenantId,
        userId: ctx.user.id,
        decisionType: "assessment_completion",
        inputSnapshotJson: JSON.stringify({ sessionId: input.sessionId, answers: answers.length }),
        outputSnapshotJson: JSON.stringify({
          overallScore: results.overallScore,
          credibilityScore,
          riskScore,
          capabilityScores: capabilityScoresFlat,
          readiness: results.readiness,
        }),
        precedenceAppliedJson: JSON.stringify({ modelVersion: "adaptive-v2" }),
      });

      await db
        .update(assessmentSessions)
        .set({ state: "completed", completedAt: new Date() })
        .where(eq(assessmentSessions.id, input.sessionId));

      await db.insert(auditLogs).values({
        id: nanoid(),
        tenantId: ctx.user.tenantId,
        actorUserId: ctx.user.id,
        action: "assessment.session.completed",
        targetType: "assessment_session",
        targetId: input.sessionId,
        metadataJson: JSON.stringify({
          overallScore: results.overallScore,
          credibilityBand,
          riskBand: results.riskBand,
          readiness: results.readiness.state,
          modelVersion: "adaptive-v2",
        }),
      });

      // R11: Create revalidation schedule based on readiness state and tenant settings
      try {
        // Fetch tenant-specific revalidation intervals (fall back to defaults)
        const tSettings = await db
          .select()
          .from(tenantSettings)
          .where(eq(tenantSettings.tenantId, ctx.user.tenantId))
          .limit(1);
        const daysLow = tSettings[0]?.revalidationDaysLow ?? 90;
        const daysMedium = tSettings[0]?.revalidationDaysMedium ?? 60;
        const daysHigh = tSettings[0]?.revalidationDaysHigh ?? 30;

        // Map readiness state to revalidation interval
        // ReadinessState = "safe" | "at_risk" | "unsafe" | "unknown"
        const revalDays =
          results.readiness.state === "safe" ? daysLow :
          results.readiness.state === "at_risk" ? daysMedium :
          daysHigh; // unsafe or unknown — highest urgency

        const dueAt = new Date();
        dueAt.setDate(dueAt.getDate() + revalDays);

        const triggerReason =
          results.readiness.state === "safe"
            ? `Routine revalidation — ${daysLow}-day cycle (safe readiness state)`
            : results.readiness.state === "at_risk"
            ? `Enhanced monitoring — ${daysMedium}-day cycle (at-risk readiness state)`
            : `Priority revalidation — ${daysHigh}-day cycle (${results.readiness.state} readiness state)`;

        // Cancel any existing pending revalidation schedules for this user
        await db
          .update(revalidationSchedules)
          .set({ status: "superseded" })
          .where(
            and(
              eq(revalidationSchedules.userId, ctx.user.id),
              eq(revalidationSchedules.status, "pending")
            )
          );

        // Insert new revalidation schedule
        await db.insert(revalidationSchedules).values({
          id: nanoid(),
          userId: ctx.user.id,
          dueAt,
          triggerReason,
          status: "pending",
        });
       } catch (revalErr) {
        // Non-fatal — log but do not block session completion
        console.warn("[assessment] R11: Failed to create revalidation schedule:", revalErr);
      }
      // I2: Wire assessment completion into the AIL pipeline (non-fatal, fire-and-forget)
      try {
        // Build signal deltas from all answers for the AIL signal ledger
        const ailSignalDeltas: Record<string, number> = {};
        for (const ans of answers) {
          try {
            const deltas = typeof ans.signalDeltasJson === "string"
              ? JSON.parse(ans.signalDeltasJson as string) as Record<string, number>
              : (ans.signalDeltasJson as Record<string, number>) ?? {};
            for (const [k, v] of Object.entries(deltas)) {
              ailSignalDeltas[k] = (ailSignalDeltas[k] ?? 0) + v;
            }
          } catch {}
        }
        const ailFailureModes = results.failureModes.modes ?? [];
        await processAssessmentThroughAIL({
          userId: ctx.user.id,
          tenantId: ctx.user.tenantId,
          assessmentId: input.sessionId,
          signalDeltas: ailSignalDeltas,
          failureModesTriggered: ailFailureModes,
          finalScore: results.overallScore,
        });
      } catch (ailErr) {
        console.warn("[assessment] I2: AIL bridge call failed (non-fatal):", ailErr);
      }
      return {
        overallScore: results.overallScore,
        credibilityScore,
        credibilityBand,
        riskScore,
        riskBand: results.riskBand,
        readiness: results.readiness,
        capabilityScores: results.capabilityScores,
        signalScores: results.signalScores,
        narrative: results.narrative,
        llmNarrative: llmNarrative ?? null,
        confidenceProfile: results.confidenceProfile,
        failureModes: results.failureModes,
        contradictions: results.contradictions,
        gamingAnalysis: results.gamingAnalysis,
        modelVersion: "adaptive-v2",
      };
    }),

  // ── Get full results for a completed session ───────────────────────────────
  results: protectedProcedure
    .input(z.object({ sessionId: z.string() }))
    .query(async ({ input, ctx }) => {
      const db = await getDb();
      if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR" });
      const session = await db
        .select()
        .from(assessmentSessions)
        .where(
          and(
            eq(assessmentSessions.id, input.sessionId),
            eq(assessmentSessions.userId, ctx.user.id)
          )
        )
        .limit(1);
      if (!session[0]) throw new TRPCError({ code: "NOT_FOUND" });
      const score = await db
        .select()
        .from(assessmentScores)
        .where(eq(assessmentScores.sessionId, input.sessionId))
        .limit(1);
      if (!score[0]) return { session: session[0], score: null };

      let breakdown: Record<string, unknown> = {};
      try {
        breakdown = (typeof score[0].scoreBreakdownJson === "string"
          ? JSON.parse(score[0].scoreBreakdownJson as string)
          : (score[0].scoreBreakdownJson ?? {})) as Record<string, unknown>;
      } catch {}

      const rawCapScores = (breakdown.capabilityScores ?? {}) as Record<string, number>;
      const enrichedCapScores: Record<string, { score: number; displayName: string; colour: string }> = {};
      for (const [key, val] of Object.entries(rawCapScores)) {
        enrichedCapScores[key] = {
          score: val as number,
          displayName: CAPABILITY_DISPLAY[key] ?? key,
          colour: CAPABILITY_COLOURS[key] ?? "#4477AA",
        };
      }

       // T3-9: Fetch previous completed sessions for longitudinal tracking
      const previousSessions = await db
        .select()
        .from(assessmentSessions)
        .where(
          and(
            eq(assessmentSessions.userId, ctx.user.id),
            eq(assessmentSessions.tenantId, ctx.user.tenantId),
            eq(assessmentSessions.state, "completed")
          )
        )
        .orderBy(assessmentSessions.completedAt)
        .limit(10);
      const longitudinalData = await Promise.all(
        previousSessions.map(async s => {
          const prevScore = await db
            .select()
            .from(assessmentScores)
            .where(eq(assessmentScores.sessionId, s.id))
            .limit(1);
          if (!prevScore[0]) return null;
          let prevBreakdown: Record<string, unknown> = {};
          try {
            prevBreakdown = (typeof prevScore[0].scoreBreakdownJson === "string"
              ? JSON.parse(prevScore[0].scoreBreakdownJson as string)
              : (prevScore[0].scoreBreakdownJson ?? {})) as Record<string, unknown>;
          } catch {}
          const prevCapScores = (prevBreakdown.capabilityScores ?? {}) as Record<string, number>;
          return {
            sessionId: s.id,
            completedAt: s.completedAt,
            overallScore: parseFloat(String(prevScore[0].overallScore)),
            capabilityScores: prevCapScores,
            readinessState: (prevBreakdown.readiness as { state?: string })?.state ?? "unknown",
          };
        })
      );
      return {
        session: session[0],
        score: {
          ...score[0],
          overallScore: parseFloat(String(score[0].overallScore)),
          breakdown: {
            ...breakdown,
            capabilityScores: enrichedCapScores,
          },
        },
        longitudinalData: longitudinalData.filter(Boolean),
      };
    }),
  // ── Get user's assessment history ──────────────────────────────────────────
  history: protectedProcedure
    .input(z.object({ userId: z.string().optional() }))
    .query(async ({ input, ctx }) => {
      const db = await getDb();
      if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR" });
      const targetUserId = input.userId ?? ctx.user.id;
      const sessions = await db
        .select()
        .from(assessmentSessions)
        .where(
          and(
            eq(assessmentSessions.userId, targetUserId),
            eq(assessmentSessions.tenantId, ctx.user.tenantId)
          )
        )
        .orderBy(desc(assessmentSessions.createdAt))
        .limit(20);
      const withScores = await Promise.all(
        sessions.map(async s => {
          const score = await db
            .select()
            .from(assessmentScores)
            .where(eq(assessmentScores.sessionId, s.id))
            .limit(1);
          let breakdown: Record<string, unknown> = {};
          try {
            breakdown = (typeof score[0]?.scoreBreakdownJson === "string"
              ? JSON.parse(score[0].scoreBreakdownJson as string)
              : (score[0]?.scoreBreakdownJson ?? {})) as Record<string, unknown>;
          } catch {}
          // T2-7: Include answeredCount for in-progress sessions
          let answeredCount = 0;
          if (s.state === "in_progress") {
            const answers = await db
              .select({ id: assessmentAnswers.id })
              .from(assessmentAnswers)
              .where(eq(assessmentAnswers.sessionId, s.id));
            answeredCount = answers.length;
          }
          return {
            ...s,
            answeredCount: s.state === "in_progress" ? answeredCount : undefined,
            score: score[0] ? {
              ...score[0],
              overallScore: parseFloat(String(score[0].overallScore)),
              primaryState: (breakdown.readiness as { state?: string })?.state ?? null,
              capabilityScores: (breakdown.capabilityScores as Record<string, number>) ?? null,
            } : null,
          };
        })
      );
      return withScores;
    }),

  // ── Admin: list assessment items ────────────────────────────────────────────
  adminItems: protectedProcedure
    .input(z.object({
      blueprintId: z.string().optional(),
      domain: z.string().optional(),
      riskLevel: z.string().optional(),
      difficulty: z.number().int().min(1).max(3).optional(),
      search: z.string().optional(),
      status: z.string().optional(),
      page: z.number().int().min(1).default(1),
      pageSize: z.number().int().min(1).max(100).default(50),
    }))
    .query(async ({ input }) => {
      const db = await getDb();
      if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR" });
      const conditions: ReturnType<typeof eq>[] = [];
      if (input.blueprintId) conditions.push(eq(assessmentItems.blueprintId, input.blueprintId));
      if (input.status) conditions.push(eq(assessmentItems.status, input.status as 'published' | 'draft' | 'archived'));
      if (input.difficulty) conditions.push(eq(assessmentItems.difficulty, input.difficulty));
      const allItems = await db
        .select()
        .from(assessmentItems)
        .where(conditions.length > 0 ? and(...conditions) : undefined)
        .orderBy(desc(assessmentItems.createdAt))
        .limit(1000);
      const filtered = allItems.filter((item) => {
        const meta = (typeof item.metadataJson === 'object' ? item.metadataJson : {}) as Record<string, unknown>;
        if (input.domain && meta.domain !== input.domain) return false;
        if (input.riskLevel && meta.risk_level !== input.riskLevel) return false;
        if (input.search) {
          const q = input.search.toLowerCase();
          const title = ((meta.title as string) || item.prompt || '').toLowerCase();
          const scenario = ((meta.scenario as string) || '').toLowerCase();
          if (!title.includes(q) && !scenario.includes(q)) return false;
        }
        return true;
      });
      const total = filtered.length;
      const offset = (input.page - 1) * input.pageSize;
      const items = filtered.slice(offset, offset + input.pageSize);
      return { items, total, page: input.page, pageSize: input.pageSize };
    }),

  // ── Admin: update assessment item status ────────────────────────────────────
  adminUpdateItemStatus: protectedProcedure
    .input(z.object({
      itemId: z.string(),
      status: z.enum(["draft", "published", "archived"]),
    }))
    .mutation(async ({ input }) => {
      const db = await getDb();
      if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR" });
      await db
        .update(assessmentItems)
        .set({ status: input.status })
        .where(eq(assessmentItems.id, input.itemId));
      return { success: true };
    }),
});
